from django.contrib.auth import get_user_model
from django.test import TestCase
from django.urls import reverse

from .models import Category, Ingredient, Recipe, RecipePhoto, Step

User = get_user_model()


def make_user(username='cook', password='pw-verylong-123'):
    return User.objects.create_user(username=username, password=password)


def make_recipe(author, name='Red Beans', **kwargs):
    return Recipe.objects.create(author=author, name=name, **kwargs)


def recipe_post_data(**overrides):
    """Valid POST payload for the create/update view (recipe + 3 formsets)."""
    data = {
        'name': 'Test Soup',
        'description': 'Tasty and warm',
        'cuisine': 'Italian',
        'prep_minutes': '10',
        'cook_minutes': '20',
        'servings': '4',
        'difficulty': 'easy',
        'calories': '200',
        'protein_g': '10',
        'carbs_g': '30',
        'fat_g': '5',
        'ingredients-TOTAL_FORMS': '1',
        'ingredients-INITIAL_FORMS': '0',
        'ingredients-MIN_NUM_FORMS': '0',
        'ingredients-MAX_NUM_FORMS': '1000',
        'ingredients-0-quantity': '2',
        'ingredients-0-unit': 'cups',
        'ingredients-0-text': 'flour',
        'ingredients-0-order': '0',
        'steps-TOTAL_FORMS': '1',
        'steps-INITIAL_FORMS': '0',
        'steps-MIN_NUM_FORMS': '0',
        'steps-MAX_NUM_FORMS': '1000',
        'steps-0-instruction': 'Mix it all together',
        'steps-0-order': '0',
        'photos-TOTAL_FORMS': '0',
        'photos-INITIAL_FORMS': '0',
        'photos-MIN_NUM_FORMS': '0',
        'photos-MAX_NUM_FORMS': '1000',
    }
    data.update(overrides)
    return data


class CategoryModelTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        cat = Category.objects.create(name='Side Dishes')
        self.assertEqual(cat.slug, 'side-dishes')

    def test_explicit_slug_is_preserved(self):
        cat = Category.objects.create(name='Breakfast', slug='morning')
        self.assertEqual(cat.slug, 'morning')

    def test_str_and_absolute_url(self):
        cat = Category.objects.create(name='Dessert')
        self.assertEqual(str(cat), 'Dessert')
        self.assertEqual(
            cat.get_absolute_url(),
            reverse('cookbook:category_detail', kwargs={'slug': 'dessert'}),
        )


class RecipeModelTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = make_user()

    def test_str_and_absolute_url(self):
        recipe = make_recipe(self.user, name='Gumbo')
        self.assertEqual(str(recipe), 'Gumbo')
        self.assertEqual(
            recipe.get_absolute_url(),
            reverse('cookbook:recipe_detail', kwargs={'pk': recipe.pk}),
        )

    def test_total_minutes_none_when_both_unset(self):
        recipe = make_recipe(self.user)
        self.assertIsNone(recipe.total_minutes)

    def test_total_minutes_sums_and_treats_missing_as_zero(self):
        self.assertEqual(make_recipe(self.user, prep_minutes=10, cook_minutes=20).total_minutes, 30)
        self.assertEqual(make_recipe(self.user, prep_minutes=15).total_minutes, 15)
        self.assertEqual(make_recipe(self.user, cook_minutes=5).total_minutes, 5)

    def test_has_nutrition(self):
        self.assertFalse(make_recipe(self.user).has_nutrition)
        self.assertTrue(make_recipe(self.user, calories=100).has_nutrition)
        self.assertTrue(make_recipe(self.user, protein_g=3).has_nutrition)


class IngredientStepPhotoModelTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.recipe = make_recipe(make_user())

    def test_ingredient_display_joins_present_parts(self):
        full = Ingredient(recipe=self.recipe, quantity='2', unit='cups', text='flour')
        self.assertEqual(full.display, '2 cups flour')
        self.assertEqual(str(full), '2 cups flour')

    def test_ingredient_display_skips_blank_parts(self):
        bare = Ingredient(recipe=self.recipe, text='salt')
        self.assertEqual(bare.display, 'salt')

    def test_step_str(self):
        step = Step(recipe=self.recipe, instruction='Boil the water thoroughly', order=1)
        self.assertIn('Step 1', str(step))
        self.assertIn('Boil', str(step))

    def test_photo_str_uses_caption_then_fallback(self):
        self.assertEqual(str(RecipePhoto(recipe=self.recipe, caption='Plated')), 'Plated')
        self.assertIn('Photo', str(RecipePhoto(recipe=self.recipe)))


class RecipeListViewTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = make_user()
        cls.dinner = Category.objects.create(name='Dinner')
        cls.dessert = Category.objects.create(name='Dessert')
        cls.gumbo = make_recipe(cls.user, name='Chicken Gumbo', description='cajun stew')
        cls.gumbo.categories.add(cls.dinner)
        Ingredient.objects.create(recipe=cls.gumbo, text='okra')
        cls.cake = make_recipe(cls.user, name='Carrot Cake', description='sweet')
        cls.cake.categories.add(cls.dessert)

    def test_list_shows_all_recipes(self):
        resp = self.client.get(reverse('cookbook:recipe_list'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Chicken Gumbo')
        self.assertContains(resp, 'Carrot Cake')

    def test_search_matches_name(self):
        resp = self.client.get(reverse('cookbook:recipe_list'), {'q': 'gumbo'})
        self.assertContains(resp, 'Chicken Gumbo')
        self.assertNotContains(resp, 'Carrot Cake')

    def test_search_matches_ingredient_text(self):
        resp = self.client.get(reverse('cookbook:recipe_list'), {'q': 'okra'})
        self.assertContains(resp, 'Chicken Gumbo')
        self.assertNotContains(resp, 'Carrot Cake')
        self.assertEqual(resp.context['query'], 'okra')

    def test_category_filter(self):
        resp = self.client.get(
            reverse('cookbook:category_detail', kwargs={'slug': 'dessert'})
        )
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Carrot Cake')
        self.assertNotContains(resp, 'Chicken Gumbo')
        self.assertEqual(resp.context['category'], self.dessert)

    def test_unknown_category_404s(self):
        resp = self.client.get(
            reverse('cookbook:category_detail', kwargs={'slug': 'nope'})
        )
        self.assertEqual(resp.status_code, 404)


class RecipeDetailViewTests(TestCase):
    def test_detail_renders(self):
        recipe = make_recipe(make_user(), name='Jambalaya', servings=6)
        resp = self.client.get(recipe.get_absolute_url())
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Jambalaya')


class RecipeCreateViewTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = make_user()
        cls.category = Category.objects.create(name='Dinner')

    def test_anonymous_redirected_to_login(self):
        resp = self.client.get(reverse('cookbook:recipe_create'))
        self.assertEqual(resp.status_code, 302)
        self.assertIn(reverse('login'), resp.url)

    def test_authenticated_get_renders_blank_form(self):
        self.client.force_login(self.user)
        resp = self.client.get(reverse('cookbook:recipe_create'))
        self.assertEqual(resp.status_code, 200)
        self.assertIn('ingredient_formset', resp.context)

    def test_create_saves_recipe_author_and_children(self):
        self.client.force_login(self.user)
        resp = self.client.post(
            reverse('cookbook:recipe_create'),
            recipe_post_data(categories=[self.category.pk]),
        )
        self.assertEqual(resp.status_code, 302)
        recipe = Recipe.objects.get(name='Test Soup')
        self.assertEqual(recipe.author, self.user)
        self.assertEqual(recipe.ingredients.count(), 1)
        self.assertEqual(recipe.ingredients.first().display, '2 cups flour')
        self.assertEqual(recipe.steps.count(), 1)
        self.assertIn(self.category, recipe.categories.all())

    def test_invalid_child_formset_rerenders_without_saving(self):
        self.client.force_login(self.user)
        # order is a required PositiveIntegerField on the ingredient row.
        resp = self.client.post(
            reverse('cookbook:recipe_create'),
            recipe_post_data(**{'ingredients-0-order': 'not-a-number'}),
        )
        self.assertEqual(resp.status_code, 200)
        self.assertFalse(Recipe.objects.filter(name='Test Soup').exists())


class RecipeUpdateDeleteViewTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.owner = make_user('owner')
        cls.other = make_user('intruder')

    def setUp(self):
        self.recipe = make_recipe(self.owner, name='My Recipe')

    def test_owner_can_update(self):
        self.client.force_login(self.owner)
        resp = self.client.post(
            reverse('cookbook:recipe_update', kwargs={'pk': self.recipe.pk}),
            recipe_post_data(name='Renamed'),
        )
        self.assertEqual(resp.status_code, 302)
        self.recipe.refresh_from_db()
        self.assertEqual(self.recipe.name, 'Renamed')

    def test_non_owner_cannot_update(self):
        self.client.force_login(self.other)
        resp = self.client.get(
            reverse('cookbook:recipe_update', kwargs={'pk': self.recipe.pk})
        )
        self.assertEqual(resp.status_code, 403)

    def test_owner_can_delete(self):
        self.client.force_login(self.owner)
        resp = self.client.post(
            reverse('cookbook:recipe_delete', kwargs={'pk': self.recipe.pk})
        )
        self.assertRedirects(resp, reverse('cookbook:recipe_list'))
        self.assertFalse(Recipe.objects.filter(pk=self.recipe.pk).exists())

    def test_non_owner_cannot_delete(self):
        self.client.force_login(self.other)
        resp = self.client.post(
            reverse('cookbook:recipe_delete', kwargs={'pk': self.recipe.pk})
        )
        self.assertEqual(resp.status_code, 403)
        self.assertTrue(Recipe.objects.filter(pk=self.recipe.pk).exists())
